- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: "Destroy Azure Deploy  Resource group {{ resource_group_name }}"
      azure_rm_deployment:
        state: absent
        subscription_id: "{{ subscriptionID }}"
        resource_group_name: "{{ resource_group_name }}"
################################################
####  Create basic infra components
################################################
    - name: "Create Azure Deploy {{ resource_group_name }}"
      azure_rm_deployment:
        state: present
        subscription_id: "{{ subscriptionID }}"
        resource_group_name: "{{ resource_group_name }}"
        template_link: 'https://raw.githubusercontent.com/ivanthelad/ansible-azure/master/infra.json'
        location: northeurope
      register: azure_vm
################################################
####  Create basic Master node, this exposes 8443 and 22 as a public ports on a public ip , in future this will be a jump host
###   we use this node to jump into the other nodes
################################################
    - name: Create Master Deployment
      with_dict: "{{ masters }}"
      azure_rm_deployment:
        deployment_mode: incremental
        state: present
        subscription_id: "{{ subscriptionID }}"
        resource_group_name: "{{ resource_group_name }}"
        location: northeurope
        parameters:
          image:
            value: rhel
          subnetName:
            value: masterSubnet
          virtualNetworkName:
            value: openshiftVnet
          dnsName:
            value: "master-{{ resource_group_name }}"
          adminUsername:
            value: "{{ adminUsername }}"
          vmSize:
            value: "{{ master_vmSize }}"
          adminPassword:
            value: "{{ adminPassword }}"
          vmName:
            value:  "{{ item.value.name }}"
          tags:
            value: "{{ item.value.tags }}"
          sshKeyData:
            value: "{{ sshkey }}"
        template_link: 'https://raw.githubusercontent.com/ivanthelad/ansible-azure/master/master.json'
      register: azure
    - debug: msg="the value of azure  {{ azure }}"

    - name: Add new instance to host group
      add_host: hostname={{ item['ips'][0].public_ip }} groupname=azure_vms
      with_items: azure.results[0].deployment.instances
    - set_fact:
        publicmasterdns: "{{ azure.results[0].deployment.instances[0].ips[0].dns_settings.fqdn }}"
        publicmasterip: "{{ azure.results[0].deployment.instances[0].ips[0].public_ip }}"
    - debug: msg="the value of azure  {{ azure }}"
    - debug: msg="the value of dns  {{ publicmasterdns }}"
    - debug: msg="the value of ip  {{ publicmasterip }}"
################################################
####  Only setting these values so we can manually look up. bit of a hack
################################################
    - lineinfile:
        dest: group_vars/all
        regexp: "^publicmasterdns:"
        line: "publicmasterdns: {{ publicmasterdns }}"
    - lineinfile:
        dest: group_vars/all
        regexp: "^publicmasterip:"
        line: "publicmasterip: {{ publicmasterip }}"
################################################
####  Adding the jump host to our local know hosts
################################################
- hosts: localhost
  connection: local
  tasks:
    - name: Scan the public key for master and added it to known hosts
      shell: "ssh-keyscan -H -T 10  {{ item }} >> ~/.ssh/known_hosts "
      with_items: groups['azure_vms']


################################################
#### Generating key on jump host. This then download locally to /tmp//id_rsa.tmp and shared to other newly create azure hosts on initialization
#### Rather complicated way but it avoids opening port 22 on all hosts
################################################
- hosts: azure_vms
  vars:
    publicmasterdns: "{{ hostvars['localhost']['publicmasterdns']}}"
    publicmasterip: "{{ hostvars['localhost']['publicmasterip']}}"
  user: ivan
  tasks:
    - name: Wait for SSH to come up
      wait_for: port=22 timeout=2000 state=started
    - name: echo the hostname of the vm
      shell: hostname
    - name: Generating RSA key for root
      user: name=ivan generate_ssh_key=yes
    - name: Downloading pub key
      fetch: src=/home/ivan/.ssh/id_rsa.pub dest=/tmp/id_rsa.tmp flat=yes
    - authorized_key: user="{{ adminUsername }}" key="{{ lookup('file', '/tmp/id_rsa.tmp') }}"


################################################
#### Subscribe the jump hosts. need to install bits like ansible and "atomic-openshift-utils"
################################################
- hosts: azure_vms
  user: ivan
  sudo: true
  roles:
     - { role: subscribe, rhnuser: "{{ rh_subcription_user }}", rhnpassword: "{{ rh_subcription_pass }}" }
  tasks:
    - name: Install Basic Preqes
      yum:
        name: "{{ item }}"
        state: present
      with_items:
           - git
           - vim
           - ansible
           - atomic-openshift-utils


################################################
#### because
################################################
- hosts: azure_vms
  user: ivan
  vars:
    contents: "{{ lookup('file', '/tmp/id_rsa.tmp') }}"
  tasks:
    - debug: msg="the value of foo.txt is {{ contents }}"
### infra here


################################################
#### Creating the infrastrucute nodes.
####Todo, dyncamically add the list of infra nodes to group
################################################
- hosts: localhost
  serial: 3
  connection: local
  vars:
      masterkey: "{{ lookup('file', '/tmp/id_rsa.tmp') }}"
  gather_facts: no
  tasks:
    - name: Create infra Nodes Deploy
      with_dict: "{{ infranodes }}"
      azure_rm_deployment:
        deployment_mode: incremental
        state: present
        subscription_id: "{{ subscriptionID }}"
        resource_group_name: "{{ resource_group_name }}"
        location: northeurope
        parameters:
          subnetName:
            value: infranodeSubnet
          virtualNetworkName:
            value: openshiftVnet
          adminUsername:
            value: "{{ adminUsername }}"
          vmSize:
            value: "{{ node_vmSize }}"
          adminPassword:
            value: "{{ adminPassword }}"
          image:
            value: rhel
          masterKey:
            value: "{{ masterkey }}"
          tags:
            value: "{{ item.value.tags }}"
          vmName:
            value: "{{ item.value.name }}"
          sshKeyData:
            value: "{{ sshkey }}"
        template_link: 'https://raw.githubusercontent.com/ivanthelad/ansible-azure/master/infranode.json'
        #i#template_link: 'ansible-azure/nodes.json'
      register: azureinfranodes
    - set_fact:
        routerpublicmasterip: "{{ azureinfranodes.results[0].deployment.instances[0].ips[0].public_ip }}"
    - debug: msg="the value of azure  {{ azure }}"
    - debug: msg="the value of ip  {{ routerpublicmasterip }}"

################################################
#### Creating the application nodes.
####Todo, dyncamically add the list of infra nodes to group
################################################
- hosts: localhost
  serial: 3
  connection: local
  vars:
      masterkey: "{{ lookup('file', '/tmp/id_rsa.tmp') }}"
  gather_facts: no
  tasks:
    - name: Create Nodes Deploy
      with_dict: "{{ nodes }}"
      azure_rm_deployment:
        deployment_mode: incremental
        state: present
        subscription_id: "{{ subscriptionID }}"
        resource_group_name: "{{ resource_group_name }}"
        location: northeurope
        parameters:
          subnetName:
            value: nodeSubnet
          virtualNetworkName:
            value: openshiftVnet
          adminUsername:
            value: "{{ adminUsername }}"
          vmSize:
            value: "{{ node_vmSize }}"
          adminPassword:
            value: "{{ adminPassword }}"
          image:
            value: rhel
          masterKey:
            value: "{{ masterkey }}"
          tags:
            value: "{{ item.value.tags }}"
          vmName:
            value: "{{ item.value.name }}"
          sshKeyData:
            value: "{{ sshkey }}"
        template_link: 'https://raw.githubusercontent.com/ivanthelad/ansible-azure/master/nodes.json'
        #i#template_link: 'ansible-azure/nodes.json' 
      register: azurenodes


################################################
#### This is kinda messy, While you can technially jump onto the jump machine and  call ansible playbook
####    ---  /bin/ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
####  In this case i'm using to jump host as a 'gatewayed' ansible proxy. basically proxying my ansible commands via the jump host.
#### To do this seamlessly the local machine requires the hosts to be added to know hosts
#### This the funky stuff that going on below... ohh forgive me
####
################################################
- hosts: azure_vms
  user: ivan
  tasks:
## From the jumphost scan the keys for all app nodes  and print to file
    - name: From the jumphost scan the keys for all app nodes  and print to file
      shell: "ssh-keyscan -H -T 10  {{ item.value.name }} >> /home/{{ adminUsername }}/.ssh/known_hosts "
      with_dict: "{{ nodes }}"
## From the jumphost fetch the keys for all app nodes  and save locally
    - name: From the jumphost fetch the keys for all app nodes  and save locally
      fetch: src=/home/{{ adminUsername }}/.ssh/known_hosts  dest=/tmp/{{ item.value.name }}_knownhosts flat=yes
      with_dict: "{{ nodes }}"
## From the jumphost scan the keys for all infranodes  and print to file
    - name:  From the jumphost scan the keys for all infranodes  and print to file
      shell: "ssh-keyscan -H -T 10  {{ item.value.name }} >> /home/{{ adminUsername }}/.ssh/known_hosts "
      with_dict: "{{ infranodes }}"
## From the jumphost fetch the keys for all infra nodes  and save locally
    - name: From the jumphost fetch the keys for all infra nodes  and save locally
      fetch: src=/home/{{ adminUsername }}/.ssh/known_hosts  dest=/tmp/{{ item.value.name }}_knownhosts flat=yes
      with_dict: "{{ infranodes }}"

## From the jumphost scan the keys for all masters  and print to file
    - name: From the jumphost scan the keys for all masters  and print to file
      shell: "ssh-keyscan -H -T 10  {{ item.value.name }} >> /home/{{ adminUsername }}/.ssh/known_hosts "
      with_dict: "{{ masters }}"
## From the jumphost fetch the keys for all master nodes  and save locally
    - name:  From the jumphost fetch the keys for all master nodes  and save locally
      fetch: src=/home/{{ adminUsername }}/.ssh/known_hosts  dest=/tmp/{{ item.value.name }}_knownhosts flat=yes
      with_dict: "{{ masters }}"


#################################################
 #### This is kinda messy, I'm appending all known hosts to local file. We fetched these in the previous step
################################################
- hosts: localhost
  connection: local
  tasks:
    - name: Assemble
      shell : "cat /tmp/{{ item.value.name }}_knownhosts >> ~/.ssh/known_hosts "
      with_dict: "{{ nodes }}"
    - name: Assemble
      shell : "cat /tmp/{{ item.value.name }}_knownhosts >> ~/.ssh/known_hosts "
      with_dict: "{{ masters }}"
    - name: Assemble
      shell : "cat /tmp/{{ item.value.name }}_knownhosts >> ~/.ssh/known_hosts "
      with_dict: "{{ infranodes }}"


## copy the ansible templated file (this is step 2 )
#################################################
 #### This may not be needed but its preparing the njumphost/master
################################################
- hosts: azure_vms
  vars:
    publicmasterdns: "{{ hostvars['localhost']['publicmasterdns']}}"
    publicmasterip: "{{ hostvars['localhost']['publicmasterip']}}"
  user: ivan
  sudo: true
  roles:
     - { role: prepare }


#################################################
 #### Heres the real business. Subscribing all nodes and masters Via jump host
################################################
- hosts: gatewayed-masters:gatewayed-nodes
  serial: 4
  vars:
    publicmasterdns: "{{ hostvars['localhost']['publicmasterdns']}}"
    publicmasterip: "{{ hostvars['localhost']['publicmasterip']}}"
    ansible_ssh_common_args: -o ProxyCommand="ssh -W %h:%p -q {{ adminUsername }}@{{ publicmasterip }}"
  user: ivan
  sudo: true
  tasks:
      - debug : msg=" {{ ansible_ssh_common_args }} "
  roles:
    - { role: subscribe, rhnuser: "{{ rh_subcription_user }}", rhnpassword: "{{ rh_subcription_pass }}" }

#################################################
 #### Heres the real business. Preparing only master. Via jump host
 #### Prepare separate mount points for things like etcd
################################################
- hosts: gatewayed-masters
  vars:
    publicmasterdns: "{{ hostvars['localhost']['publicmasterdns']}}"
    publicmasterip: "{{ hostvars['localhost']['publicmasterip']}}"
    ansible_ssh_common_args: -o ProxyCommand="ssh -W %h:%p -q {{ adminUsername }}@{{ publicmasterip }}"
  user: "{{ adminUsername }}"
  sudo: true
  tasks:
  - name: Install Master stuff
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - atomic-openshift-utils
  - name: upgrade all packages
    yum: name=* state=latest
  - name: creating new LVM volume group
    lvg: vg={{ create_vgname }} pvs={{ docker_storage_device }} state=present
  - lineinfile:
      dest: /etc/ansible/ansible.cfg
      regexp: "^#log_path"
      line: "log_path = /tmp/ansible.log"

#################################################
 #### Heres the real business. Preparing only master. Via jump host
################################################
- hosts: gatewayed-masters
  vars:
    publicmasterdns: "{{ hostvars['localhost']['publicmasterdns']}}"
    publicmasterip: "{{ hostvars['localhost']['publicmasterip']}}"
    ansible_ssh_common_args: -o ProxyCommand="ssh -W %h:%p -q {{ adminUsername }}@{{ publicmasterip }}"
  user: "{{ adminUsername }}"
  sudo: true
  ## TODO, need to check this. stopped working
  roles:
    - { role: lv_create, create_lvname: 'registry-lv', create_vgname: 'docker_vg', new_mntp: '/mnt/registry', create_lvsize: '40960' }

#################################################
 #### Heres the real business. Preparing nodes(including infra).  See prereqs_azure for details. Via jump host
################################################
- hosts: gatewayed-nodes
  serial: 3
  vars:
    publicmasterdns: "{{ hostvars['localhost']['publicmasterdns']}}"
    publicmasterip: "{{ hostvars['localhost']['publicmasterip']}}"
    ansible_ssh_common_args: -o ProxyCommand="ssh -W %h:%p -q {{ adminUsername }}@{{ publicmasterip }}"
  user: "{{ adminUsername }}"
  sudo: true
  roles:
    - { role: prereqs_azure  }
    - { role: storage_docker }

#################################################
 #### Heres the real business. Preparing nodes(including infra).  See prereqs_azure for details. Via jump host
################################################
#- hosts: gatewayed-nodes
#  serial: 3
#  vars:
#    publicmasterdns: "{{ hostvars['localhost']['publicmasterdns']}}"
#    publicmasterip: "{{ hostvars['localhost']['publicmasterip']}}"
#    ansible_ssh_common_args: -o ProxyCommand="ssh -W %h:%p -q {{ adminUsername }}@{{ publicmasterip }}"
#  user: "{{ adminUsername }}"
#  sudo: true
#  roles:
#    - { role: storage_docker }
#

################################################
 #### Installing openshift
################################################
- hosts: gatewayed-masters
  user: ivan
  force_handlers: yes
  tasks:
  - name: install openshift
    notify: Get Ansible log files
    command: "/bin/ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml  "
    args:
      chdir: /home/ivan

- hosts: localhost
  connection: local
  tasks:
    - debug: msg="Congrats. Openshift should be now up and running under https://{{ publicmasterdns }}:8443/"
    - debug: msg="You can login using your user {{ adminUsername }}@{{ publicmasterip }}"
    - debug: msg="You will need to configure your dns to talk to the openshift router under  {{ routerpublicmasterip }}"


- handlers:
    - name: Get Ansible log files

      fetch:
        src: /tmp/ansible.log
        dest: "{{ resource_group_name }}_ansible.log"
        flat: yes

### todo, get log of ansible file for shits and giggles
### Todo, Simplify by defiing a jump host/gateway
## Todo,  commit code
## todo, the mnt_points need to be adjuested to reflect realworld mounts on the masters
## Seperate the masters from the nodes
## todo, Print out endpoint of master and router
## todo, Perhaps setup router and stuff




## step 1 git clone
## step 2 update properties in clone file (docker storage). Best bet is to user group_vars/all  and populate that file accordingly
# - add group vars to the previous step
## step 3
#### ansible-playbook -i /etc/ansible/prepare.hosts playbooks/subscribe.yml   --user=ivan --become-method=sudo --become --private-key=~/.ssh/id_rsa
#### ansible-playbook -i /etc/ansible/prepare.hosts playbooks/configall.azure.yml   --user=ivan --become-method=sudo --become --private-key=~/.ssh/id_rsa

#- hosts: azure_vms
#  tasks:
#   - name: Copy host file to master
#     template:
#       src: /Users/imckinle/Projects/openshift/azure-ansible/set-vars.j2
#       dest: /Users/imckinle/Projects/openshift/azure-ansible/set-vars.2
#    - name: Add new instance to host group
#      add_host: hostname={{ item['ips'][0].public_ip }} groupname=azure_vms
#      with_items: azure.deployment.instances

#https://docs.ansible.com/ansible/azure_rm_deployment_module.html
